/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shawon
 */
import java.sql.*;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ButtonModel;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
//import static javaconnect.connect;
//import static javaconnect.connect;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;
import textfield.SearchOption;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import textfield.SearchOptinEvent;

public class managerlistmanager1 extends javax.swing.JFrame {

    /**
     * Creates new form contact
     */
    
    Connection co = null;
    PreparedStatement pst=null;
    id getid=new id();
    public managerlistmanager1() {
        initComponents();
        
          
//        try {
//            String query = "SELECT * FROM signupmanager";
//            pst = co.prepareStatement(query);
//            
//            ResultSet rs = pst.executeQuery();
//            DefaultTableModel tm1 = (DefaultTableModel)jTable1.getModel();
//            tm1.setRowCount(0);
//            while(rs.next()){
//                Object obj[] = {rs.getInt("id"), rs.getString("name"), rs.getString("email"), rs.getString("club"),rs.getInt("year"),rs.getString("username")};
//                tm1.addRow(obj);
//            }
//        } 
//        catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
        //Shawon
//       txt.addEventOptionSelected((SearchOption option, int index) -> {
//           txt.setHint("Search by " + option.getName() + "...");
//        });
//        txt.addOption(new SearchOption("Name", new ImageIcon(getClass().getResource("/test/user.png"))));
//        txt.addOption(new SearchOption("Tel", new ImageIcon(getClass().getResource("/test/tel.png"))));
//        txt.addOption(new SearchOption("Email", new ImageIcon(getClass().getResource("/test/email.png"))));
//        txt.addOption(new SearchOption("Address", new ImageIcon(getClass().getResource("/test/address.png"))));
//        
        //shawon
        
         try {
            co = connnect.con();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldSearchOption1 = new textfield.TextFieldSearchOption();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kButton11 = new com.k33ptoo.components.KButton();
        jPanel17 = new javax.swing.JPanel();
        kButton26 = new com.k33ptoo.components.KButton();
        kButton27 = new com.k33ptoo.components.KButton();
        kButton28 = new com.k33ptoo.components.KButton();
        kButton29 = new com.k33ptoo.components.KButton();
        kButton30 = new com.k33ptoo.components.KButton();
        kButton31 = new com.k33ptoo.components.KButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kButton12 = new com.k33ptoo.components.KButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profile Details");

        textFieldSearchOption1.setText("Search");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(928, 629));

        jPanel1.setBackground(new java.awt.Color(50, 0, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(928, 629));
        jPanel1.setPreferredSize(new java.awt.Dimension(928, 629));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "E-mail", "Club", "Birth_Year", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kButton11.setText("Refresh");
        kButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton11.setkEndColor(new java.awt.Color(204, 0, 51));
        kButton11.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton11.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton11.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton11.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(34, 0, 41));

        kButton26.setText("Manager List");
        kButton26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton26.setkBorderRadius(15);
        kButton26.setkEndColor(new java.awt.Color(50, 0, 60));
        kButton26.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton26.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton26.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton26.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton26.setkStartColor(new java.awt.Color(50, 0, 60));
        kButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton26ActionPerformed(evt);
            }
        });

        kButton27.setText("Player List");
        kButton27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton27.setkBorderRadius(15);
        kButton27.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton27.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton27.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton27.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton27.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton27.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton27ActionPerformed(evt);
            }
        });

        kButton28.setText("My Team");
        kButton28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton28.setkBorderRadius(15);
        kButton28.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton28.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton28.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton28.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton28.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton28.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton28ActionPerformed(evt);
            }
        });

        kButton29.setBackground(new java.awt.Color(104, 42, 178));
        kButton29.setText("Profile");
        kButton29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton29.setkBorderRadius(15);
        kButton29.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton29.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton29.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton29.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton29.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton29.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton29ActionPerformed(evt);
            }
        });

        kButton30.setText("Contact Us");
        kButton30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton30.setkBorderRadius(15);
        kButton30.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton30.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton30.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton30.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton30.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton30.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton30ActionPerformed(evt);
            }
        });

        kButton31.setText("My Squad");
        kButton31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton31.setkBorderRadius(15);
        kButton31.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton31.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton31.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton31.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton31.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton31.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(kButton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfp/Search2.png"))); // NOI18N

        kButton12.setText("View Details");
        kButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton12.setkEndColor(new java.awt.Color(204, 0, 51));
        kButton12.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton12.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton12.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton12.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        
        try {
            String query = "SELECT * FROM signupmanager";
            pst = co.prepareStatement(query);
            
            ResultSet rs = pst.executeQuery();
            DefaultTableModel tm1 = (DefaultTableModel)jTable1.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
                Object obj[] = {rs.getInt("id"), rs.getString("name"), rs.getString("email"), rs.getString("club"),rs.getInt("year"),rs.getString("username")};
                tm1.addRow(obj);
            }
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
//        homepage obj=new homepage();
//        obj.setVisible(true);
//        obj.setResizable(false);
//        dispose();
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton26ActionPerformed
        // TODO add your handling code here:
        managerlistmanager1 obj=new managerlistmanager1();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton26ActionPerformed

    private void kButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton27ActionPerformed
        // TODO add your handling code here:
       newplayerlist obj=new newplayerlist();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton27ActionPerformed

    private void kButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton28ActionPerformed
        // TODO add your handling code here:
        myteam obj=new myteam();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton28ActionPerformed

    private void kButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton30ActionPerformed
        // TODO add your handling code here:
        contactmanager obj=new contactmanager();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton30ActionPerformed

    private void kButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton31ActionPerformed
        // TODO add your handling code here:
        mysquad obj=new mysquad();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton31ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(null, "kiree");
    }//GEN-LAST:event_jTable1MouseClicked

    private void kButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton29ActionPerformed
        // TODO add your handling code here:
        managerprofile obj=new managerprofile();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton29ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
        final TableRowSorter<TableModel> sorter=new TableRowSorter<>(dtm);
        jTable1.setRowSorter(sorter);
        String txt=jTextField1.getText();
        if(txt.length()==0)
        {
            sorter.setRowFilter(null);
            
        }
        else
        {
            sorter.setRowFilter(RowFilter.regexFilter(txt));
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        
        //Inserting here
        
        
        int row = jTable1.getSelectedRow();
//        System.out.println(row);
        String k  = jTable1.getModel().getValueAt(row,0).toString();
        System.out.println(k);
        String s= k;
        
        getid.x= Integer.parseInt(s);
        
        managerdetails obj=new managerdetails();
        obj.setVisible(true);
        obj.setResizable(false);
//        dispose();
        
    }//GEN-LAST:event_kButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerlistmanager1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton12;
    private com.k33ptoo.components.KButton kButton26;
    private com.k33ptoo.components.KButton kButton27;
    private com.k33ptoo.components.KButton kButton28;
    private com.k33ptoo.components.KButton kButton29;
    private com.k33ptoo.components.KButton kButton30;
    private com.k33ptoo.components.KButton kButton31;
    private textfield.TextFieldSearchOption textFieldSearchOption1;
    // End of variables declaration//GEN-END:variables
}
