/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shawon
 */
import java.sql.*;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ButtonModel;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
//import static javaconnect.connect;
//import static javaconnect.connect;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ButtonModel;
import javax.swing.JLabel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class newplayerlist extends javax.swing.JFrame {

    /**
     * Creates new form contact
     */
    
     String s, s2, s3, s4;
    
    Connection co = null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    id getid=new id();
    String k;
    public newplayerlist() {
        initComponents();
        
        
        
        //random variables
        
         s=club.getItemAt(club.getSelectedIndex());
         s2=country.getItemAt(country.getSelectedIndex());
        s3=position.getItemAt(position.getSelectedIndex());
         s4=year.getItemAt(year.getSelectedIndex());
        
        if(s.equals("Select Club"))
        {
            s="is not null";
        }
        else{
            s="="+s;
        }
        System.out.println(s);
         if(s2.equals("Country"))
        {
            s2="is not null";
        }
        else{
            s2="="+s2;
        }
        System.out.println(s2);
        
        if(s3.equals("Select Position"))
        {
            s3="is not null";
        }
        else{
            s3="="+s3;
        }
        if(s4.equals("Select Birth Year"))
        {
            s4="is not null";
        }
        else{
            s4="="+s4;
        }
        
        
        
        
        //connection
         try {
            co = connnect.con();
        } catch (Exception e) {
        }
         
         
         System.out.println(jPanel1.getName());
         
         
         //panel
         
        String sql= "SELECT * FROM signupplayer";
        try{
            pst = co.prepareStatement(sql);
            
           rs = pst.executeQuery();
           int r=0,c=0;
           
           JLabel[] labels=new JLabel[100];
               for(int i=0;i<100;i++)
               {
                 labels[i]=new JLabel();
               }
           
           int cnt=0;
           while(rs.next())
           {
//               JLabel label=new JLabel();
               labels[cnt++].setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("photo"))));
               jPanel2.add(labels[cnt-1],new org.netbeans.lib.awtextra.AbsoluteConstraints(30+r*200,30+c*200,-1,-1));
               r++;
               if(r>=3)
               {
                   r=0;
                   c++;
               }
               k=rs.getString("id");
              
                labels[cnt-1].addMouseListener(new java.awt.event.MouseAdapter() {
                    String k2 = k;
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                       playerid ob=new playerid();
                ob.p=Integer.parseInt(k2);
                playerdetails obj=new playerdetails();
                obj.setVisible(true);
                 
            }
        });
               
           }
//          jPanel2.revalidate();
//            jPanel2.repaint();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton31 = new com.k33ptoo.components.KButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        club = new javax.swing.JComboBox<>();
        country = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profile Details");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bundesliga");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(928, 629));

        jPanel1.setBackground(new java.awt.Color(50, 0, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(928, 629));
        jPanel1.setPreferredSize(new java.awt.Dimension(928, 629));

        jPanel3.setBackground(new java.awt.Color(34, 0, 41));

        kButton2.setText("Manager List");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton2.setkBorderRadius(15);
        kButton2.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton2.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("Player List");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton3.setkBorderRadius(15);
        kButton3.setkEndColor(new java.awt.Color(50, 0, 60));
        kButton3.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton3.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(50, 0, 60));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton4.setText("My Team");
        kButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton4.setkBorderRadius(15);
        kButton4.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton4.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton4.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton4.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setBackground(new java.awt.Color(104, 42, 178));
        kButton5.setText("Profile");
        kButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton5.setkBorderRadius(15);
        kButton5.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton5.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton5.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton5.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        kButton6.setText("Contact Us");
        kButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton6.setkBorderRadius(15);
        kButton6.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton6.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton6.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton6.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton31.setText("My Squad");
        kButton31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton31.setkBorderRadius(15);
        kButton31.setkEndColor(new java.awt.Color(104, 42, 178));
        kButton31.setkHoverEndColor(new java.awt.Color(50, 0, 60));
        kButton31.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton31.setkHoverStartColor(new java.awt.Color(50, 0, 60));
        kButton31.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton31.setkStartColor(new java.awt.Color(104, 42, 178));
        kButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfp/Search2.png"))); // NOI18N

        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Position", "CF", "AMF", "CMF","CB","GK","RB","RWF","LWF" }));
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Birth Year", "1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        club.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Club", "FC Barcelona", "Real Madrid", "Man City", "Arsenal", "PSG", "Bayern Munchen","Juventas", "Dortmund","AC Milan","Liverpool" }));
        club.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubActionPerformed(evt);
            }
        });

        country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Country", "Argentina", "Brazil", "Spain" ,"Germany","France","England","Norway","Portugal"}));
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(0, 153, 0));

        jPanel2.setBackground(new java.awt.Color(50, 0, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(club, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(club, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        managerlistmanager1 obj=new managerlistmanager1();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
        managerprofile obj=new managerprofile();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
        myteam obj=new myteam();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
         contactmanager obj=new contactmanager();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton31ActionPerformed
        // TODO add your handling code here:
        mysquad obj=new mysquad();
        obj.setVisible(true);
        obj.setResizable(false);
        dispose();
    }//GEN-LAST:event_kButton31ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        jPanel2.removeAll();
        String sql ="select * from signupplayer where name like '%"+jTextField1.getText()+"%' or club like '%"+jTextField1.getText()+"%'";
        System.out.println(sql);
        
////        try {
////            pst=co.prepareStatement(sql);
//////             System.out.println(555);     
////            rs=pst.executeQuery();
//////             System.out.println(555);  
////             while(rs.next())
////             {
////                 System.out.println(rs.getString("name"));
////             }
//             
//             
//                      
//        } catch (SQLException ex) {
////            Logger.getLogger(myprofile.class.getName()).log(Level.SEVERE, null, ex);
//                System.out.println("Not");
//        }
            try{
            pst = co.prepareStatement(sql);
            
           rs = pst.executeQuery();
           int r=0,c=0;
           
           JLabel[] labels=new JLabel[100];
               for(int i=0;i<100;i++)
               {
                 labels[i]=new JLabel();
               }
           
           int cnt=0;
           while(rs.next())
           {
//               JLabel label=new JLabel();
               labels[cnt++].setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("photo"))));
               jPanel2.add(labels[cnt-1],new org.netbeans.lib.awtextra.AbsoluteConstraints(30+r*200,30+c*200,-1,-1));
               r++;
               if(r>=3)
               {
                   r=0;
                   c++;
               }
               k=rs.getString("id");
              
                labels[cnt-1].addMouseListener(new java.awt.event.MouseAdapter() {
                    String k2 = k;
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                       playerid ob=new playerid();
                ob.p=Integer.parseInt(k2);
                playerdetails obj=new playerdetails();
                obj.setVisible(true);
                 
            }
        });
               
           }
          jPanel2.revalidate();
            jPanel2.repaint();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }


       
            
    }//GEN-LAST:event_jTextField1KeyPressed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
      

    }//GEN-LAST:event_jTextField1KeyTyped

    private void clubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubActionPerformed
//         TODO add your handling code here:
     jPanel2.removeAll();
        
         s=club.getItemAt(club.getSelectedIndex());
         s2=country.getItemAt(country.getSelectedIndex());
        s3=position.getItemAt(position.getSelectedIndex());
         s4=year.getItemAt(year.getSelectedIndex());
        
        if(s.equals("Select Club"))
        {
            s="is not null";
        }
        else{
            s=   "=" + "'"  +s + "'";
        }
        System.out.println(s);
         if(s2.equals("Country"))
        {
            s2="is not null";
        }
        else{
            s2=   "=" + "'"  +s2 + "'";
        }
        System.out.println(s2);
         if(s3.equals("Select Position"))
        {
            s3="is not null";
        }
        else{
            s3=   "=" + "'"  +s3 + "'";
        }
        if(s4.equals("Select Birth Year"))
        {
            s4="is not null";
        }
        else{
            s4=   "=" + "'"  +s4 + "'";
        }
        
//        String sql= "SELECT * FROM signupplayer WHERE club="+"\""+s+"\""; 
           String sql = "select * from signupplayer where club "+s+" and year "+s4+" and position "+s3+" and country "+s2;
           System.out.println(sql);
        try{
            pst = co.prepareStatement(sql);
            
           rs = pst.executeQuery();
           int r=0,c=0;
           
           JLabel[] labels=new JLabel[100];
               for(int i=0;i<100;i++)
               {
                 labels[i]=new JLabel();
               }
           
           int cnt=0;
           while(rs.next())
           {
//               JLabel label=new JLabel();
               labels[cnt++].setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("photo"))));
               jPanel2.add(labels[cnt-1],new org.netbeans.lib.awtextra.AbsoluteConstraints(30+r*200,30+c*200,-1,-1));
               r++;
               if(r>=3)
               {
                   r=0;
                   c++;
               }
               k=rs.getString("id");
              
                labels[cnt-1].addMouseListener(new java.awt.event.MouseAdapter() {
                    String k2 = k;
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                       playerid ob=new playerid();
                ob.p=Integer.parseInt(k2);
                playerdetails obj=new playerdetails();
                obj.setVisible(true);
                 
            }
        });
               
           }
          jPanel2.revalidate();
            jPanel2.repaint();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
         
    }//GEN-LAST:event_clubActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
       
          jPanel2.removeAll();
        
         s=club.getItemAt(club.getSelectedIndex());
         s2=country.getItemAt(country.getSelectedIndex());
        s3=position.getItemAt(position.getSelectedIndex());
         s4=year.getItemAt(year.getSelectedIndex());
        
        if(s.equals("Select Club"))
        {
            s="is not null";
        }
        else{
            s=   "=" + "'"  +s + "'";
        }
        System.out.println(s);
         if(s2.equals("Country"))
        {
            s2="is not null";
        }
        else{
            s2=   "=" + "'"  +s2 + "'";
        }
        System.out.println(s2);
         if(s3.equals("Select Position"))
        {
            s3="is not null";
        }
        else{
            s3=   "=" + "'"  +s3 + "'";
        }
        if(s4.equals("Select Birth Year"))
        {
            s4="is not null";
        }
        else{
            s4=   "=" + "'"  +s4 + "'";
        }
        
//        String sql= "SELECT * FROM signupplayer WHERE club="+"\""+s+"\""; 
           String sql = "select * from signupplayer where club "+s+" and year "+s4+" and position "+s3+" and country "+s2;
           System.out.println(sql);
        try{
            pst = co.prepareStatement(sql);
            
           rs = pst.executeQuery();
           int r=0,c=0;
           
           JLabel[] labels=new JLabel[100];
               for(int i=0;i<100;i++)
               {
                 labels[i]=new JLabel();
               }
           
           int cnt=0;
           while(rs.next())
           {
//               JLabel label=new JLabel();
               labels[cnt++].setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("photo"))));
               jPanel2.add(labels[cnt-1],new org.netbeans.lib.awtextra.AbsoluteConstraints(30+r*200,30+c*200,-1,-1));
               r++;
               if(r>=3)
               {
                   r=0;
                   c++;
               }
               k=rs.getString("id");
              
                labels[cnt-1].addMouseListener(new java.awt.event.MouseAdapter() {
                    String k2 = k;
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                       playerid ob=new playerid();
                ob.p=Integer.parseInt(k2);
                playerdetails obj=new playerdetails();
                obj.setVisible(true);
                 
            }
        });
               
           }
          jPanel2.revalidate();
            jPanel2.repaint();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
         
    }//GEN-LAST:event_yearActionPerformed

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
          jPanel2.removeAll();
        
         s=club.getItemAt(club.getSelectedIndex());
         s2=country.getItemAt(country.getSelectedIndex());
        s3=position.getItemAt(position.getSelectedIndex());
         s4=year.getItemAt(year.getSelectedIndex());
        
        if(s.equals("Select Club"))
        {
            s="is not null";
        }
        else{
            s=   "=" + "'"  +s + "'";
        }
        System.out.println(s);
         if(s2.equals("Country"))
        {
            s2="is not null";
        }
        else{
            s2=   "=" + "'"  +s2 + "'";
        }
        System.out.println(s2);
         if(s3.equals("Select Position"))
        {
            s3="is not null";
        }
        else{
            s3=   "=" + "'"  +s3 + "'";
        }
        if(s4.equals("Select Birth Year"))
        {
            s4="is not null";
        }
        else{
            s4=   "=" + "'"  +s4 + "'";
        }
        
//        String sql= "SELECT * FROM signupplayer WHERE club="+"\""+s+"\""; 
           String sql = "select * from signupplayer where club "+s+" and year "+s4+" and position "+s3+" and country "+s2;
           System.out.println(sql);
        try{
            pst = co.prepareStatement(sql);
            
           rs = pst.executeQuery();
           int r=0,c=0;
           
           JLabel[] labels=new JLabel[100];
               for(int i=0;i<100;i++)
               {
                 labels[i]=new JLabel();
               }
           
           int cnt=0;
           while(rs.next())
           {
//               JLabel label=new JLabel();
               labels[cnt++].setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("photo"))));
               jPanel2.add(labels[cnt-1],new org.netbeans.lib.awtextra.AbsoluteConstraints(30+r*200,30+c*200,-1,-1));
               r++;
               if(r>=3)
               {
                   r=0;
                   c++;
               }
               k=rs.getString("id");
              
                labels[cnt-1].addMouseListener(new java.awt.event.MouseAdapter() {
                    String k2 = k;
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                       playerid ob=new playerid();
                ob.p=Integer.parseInt(k2);
                playerdetails obj=new playerdetails();
                obj.setVisible(true);
                 
            }
        });
               
           }
          jPanel2.revalidate();
            jPanel2.repaint();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
         
         
    }//GEN-LAST:event_positionActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:\
          jPanel2.removeAll();
        
         s=club.getItemAt(club.getSelectedIndex());
         s2=country.getItemAt(country.getSelectedIndex());
        s3=position.getItemAt(position.getSelectedIndex());
         s4=year.getItemAt(year.getSelectedIndex());
        
        if(s.equals("Select Club"))
        {
            s="is not null";
        }
        else{
            s=   "=" + "'"  +s + "'";
        }
        System.out.println(s);
         if(s2.equals("Country"))
        {
            s2="is not null";
        }
        else{
            s2=   "=" + "'"  +s2 + "'";
        }
        System.out.println(s2);
         if(s3.equals("Select Position"))
        {
            s3="is not null";
        }
        else{
            s3=   "=" + "'"  +s3 + "'";
        }
        if(s4.equals("Select Birth Year"))
        {
            s4="is not null";
        }
        else{
            s4=   "=" + "'"  +s4 + "'";
        }
        
//        String sql= "SELECT * FROM signupplayer WHERE club="+"\""+s+"\""; 
           String sql = "select * from signupplayer where club "+s+" and year "+s4+" and position "+s3+" and country "+s2;
           System.out.println(sql);
        try{
            pst = co.prepareStatement(sql);
            
           rs = pst.executeQuery();
           int r=0,c=0;
           
           JLabel[] labels=new JLabel[100];
               for(int i=0;i<100;i++)
               {
                 labels[i]=new JLabel();
               }
           
           int cnt=0;
           while(rs.next())
           {
//               JLabel label=new JLabel();
               labels[cnt++].setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("photo"))));
               jPanel2.add(labels[cnt-1],new org.netbeans.lib.awtextra.AbsoluteConstraints(30+r*200,30+c*200,-1,-1));
               r++;
               if(r>=3)
               {
                   r=0;
                   c++;
               }
               k=rs.getString("id");
              
                labels[cnt-1].addMouseListener(new java.awt.event.MouseAdapter() {
                    String k2 = k;
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                       playerid ob=new playerid();
                ob.p=Integer.parseInt(k2);
                playerdetails obj=new playerdetails();
                obj.setVisible(true);
                 
            }
        });
               
           }
          jPanel2.revalidate();
            jPanel2.repaint();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
         
      
    }//GEN-LAST:event_countryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  jTable1 p=new jTable1();
                
                new newplayerlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> club;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton31;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
